analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
color:
  saturation: 0.6568297
  brandStrength: 0.8654217247385532
  rhythmicContrast: 0.8617201
  brandColors:
    - '#EBEBEB'
    - '#5C5C5C'
    - '#303030'
  lightness: 0.9224283
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: Agnomia
typography_spectrum: 0.8853288
